# File: cactilize.yml
# Description:
# Playbook for cactilize
#
# OS: Debian6 debian7

---
- hosts: all
  user: admin
  sudo: True
  gather_facts:  yes
  vars:
    # ABSTRACT
    deploy                : false
    webui_admin_user      : admin
    webui_admin_password  : admin
    htpassword_admin      : admin
    archi_name            : TEST
    archi_subnet          : 'localhost'
    default_community     : m6#com
    cacti_db_hostname     : localhost
    cacti_db_password     : admin
    cacti_mysql_mon_user  : admin
    cacti_mysql_mon_pass  : admin
    RRA_VG_NAME           : system
    #RRA_LV_NAME           : var_lib_rra
    RRA_LV_SIZE           : 5G
    RRA_MOUNT_POINT       : '/var/lib/rra'
    DEFAULT_IP            : 'localhost'
    WHITELIST             : ''
    cacti_server          : server

     ## User Access and Permissions
    Users:
      'spyviewer':
         htpassword          : YbXpnONCIG9V2
         password            : FleninOfAt
         full_name           : 'SPY Viewer'
         enabled             : 'on'
         must_change_password:
         permissions         :
           - View_Graphs
           - Export_Data
         policy              :
           - View_Graphs
           - View_Tree
  roles:
   - cactilize
